# Generated by Django 5.1.15 on 2026-07-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarche', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CataloguePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Numéro de la page (1, 2, 3...)')),
                ('image', models.ImageField(upload_to='catalogues/pages/')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='supermarche.cataloguenumerique')),
            ],
            options={
                'verbose_name': 'Page de catalogue',
                'verbose_name_plural': 'Pages de catalogue',
                'ordering': ['numero'],
                'unique_together': {('catalogue', 'numero')},
            },
        ),
    ]
