# Generated by Django 5.1.15 on 2026-07-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarche', '0002_cataloguepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=12, unique=True)),
                ('client_nom', models.CharField(max_length=120, verbose_name='Nom complet')),
                ('client_telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('type_recuperation', models.CharField(choices=[('retrait', 'Retrait en magasin'), ('livraison', 'Livraison à domicile')], default='retrait', max_length=12)),
                ('adresse_livraison', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('creneau_souhaite', models.DateTimeField(verbose_name='Créneau souhaité')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('confirmee', 'Confirmée'), ('prete', 'Prête (retrait)'), ('en_livraison', 'En cours de livraison'), ('recuperee', 'Récupérée / Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=15)),
                ('note_client', models.TextField(blank=True, verbose_name='Instructions particulières')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='supermarche.magasin')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire_capture', models.DecimalField(decimal_places=0, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supermarche.produit')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='supermarche.reservation')),
            ],
            options={
                'verbose_name': 'Ligne de réservation',
                'verbose_name_plural': 'Lignes de réservation',
            },
        ),
    ]
