# Generated by Django 5.1.15 on 2026-07-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarche', '0003_reservation_lignereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chapeau_en',
            field=models.TextField(blank=True, help_text='Résumé court affiché en liste', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='chapeau_fr',
            field=models.TextField(blank=True, help_text='Résumé court affiché en liste', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='contenu_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='contenu_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='titre_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='titre_fr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='avantagesfidelite',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='avantagesfidelite',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='avantagesfidelite',
            name='titre_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avantagesfidelite',
            name='titre_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bannierehero',
            name='sous_titre_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bannierehero',
            name='sous_titre_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bannierehero',
            name='texte_bouton_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bannierehero',
            name='texte_bouton_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bannierehero',
            name='titre_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bannierehero',
            name='titre_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bannieresecondaire',
            name='titre_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bannieresecondaire',
            name='titre_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cataloguenumerique',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cataloguenumerique',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='categoriefaq',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoriefaq',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chiffrecle',
            name='libelle_en',
            field=models.CharField(help_text='Ex: Magasins au Togo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chiffrecle',
            name='libelle_fr',
            field=models.CharField(help_text='Ex: Magasins au Togo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='magasin',
            name='horaires_en',
            field=models.TextField(blank=True, help_text='Ex: Lun-Sam 8h-21h / Dim 9h-18h', null=True),
        ),
        migrations.AddField(
            model_name='magasin',
            name='horaires_fr',
            field=models.TextField(blank=True, help_text='Ex: Lun-Sam 8h-21h / Dim 9h-18h', null=True),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='citation_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='citation_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='poste_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membreequipe',
            name='poste_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='avantages_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='avantages_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='profil_recherche_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='profil_recherche_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_indicatif_en',
            field=models.CharField(blank=True, help_text='Ex: 150 000 – 200 000 FCFA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='salaire_indicatif_fr',
            field=models.CharField(blank=True, help_text='Ex: 150 000 – 200 000 FCFA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offreemploi',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parametressite',
            name='description_courte_en',
            field=models.TextField(blank=True, help_text='Résumé affiché dans le <meta description>', null=True),
        ),
        migrations.AddField(
            model_name='parametressite',
            name='description_courte_fr',
            field=models.TextField(blank=True, help_text='Résumé affiché dans le <meta description>', null=True),
        ),
        migrations.AddField(
            model_name='parametressite',
            name='mentions_legales_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametressite',
            name='mentions_legales_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametressite',
            name='politique_confidentialite_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametressite',
            name='politique_confidentialite_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametressite',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parametressite',
            name='slogan_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='composition_en',
            field=models.TextField(blank=True, help_text='Ingrédients / composition', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='composition_fr',
            field=models.TextField(blank=True, help_text='Ingrédients / composition', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='conditionnement_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='conditionnement_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionfaq',
            name='question_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='questionfaq',
            name='question_fr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='questionfaq',
            name='reponse_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionfaq',
            name='reponse_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rayoncategorie',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rayoncategorie',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rayoncategorie',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rayoncategorie',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='astuce_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='astuce_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='etapes_en',
            field=models.TextField(help_text='Une étape par ligne ou HTML', null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='etapes_fr',
            field=models.TextField(help_text='Une étape par ligne ou HTML', null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients_en',
            field=models.TextField(help_text='Un ingrédient par ligne', null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients_fr',
            field=models.TextField(help_text='Un ingrédient par ligne', null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicemagasin',
            name='libelle_en',
            field=models.CharField(blank=True, help_text='Surcharge du libellé par défaut', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicemagasin',
            name='libelle_fr',
            field=models.CharField(blank=True, help_text='Surcharge du libellé par défaut', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagarticle',
            name='nom_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tagarticle',
            name='nom_fr',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
